# Generated by Django 3.2.4 on 2021-07-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0002_auto_20210716_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzas',
            name='pcategory',
            field=models.CharField(choices=[('NV', 'Non-Veg'), ('VG', 'Veg')], default='NV', max_length=12),
        ),
    ]
