# Generated by Django 3.2.4 on 2021-07-16 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
