# Generated by Django 3.2.4 on 2021-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaApp', '0007_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizzas',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='pizzas',
            field=models.CharField(max_length=100000),
        ),
    ]
